/*
 * File:           CeoInbox.cpp
 * Program:        EECS 348 Assignment 3 - CEO Email Prioritizer
 * Description:    Implements the CEO inbox commands on top of MaxHeap<Email>.
 * Inputs/Output:  Command arguments; prints NEXT and COUNT results to the terminal
 * Collaborators:  None
 * Other sources:  Code generated by Claude (Anthropic LLM), then reviewed by me.
 * Author:         Jacob Fox
 * Creation date:  09-30-2026
 * Revision date:  09-30-2026
 * Revisions:      Split single-file version into modules.
 */

#include "CeoInbox.h"
 
#include <iostream>  // terminal output
 
namespace {
 
// Remove leading/trailing spaces and tabs. O(length).
std::string trim(const std::string& s) {
    std::size_t b = s.find_first_not_of(" \t");        // first non-blank char
    if (b == std::string::npos) return "";             // all blank
    std::size_t e = s.find_last_not_of(" \t");         // last non-blank char
    return s.substr(b, e - b + 1);
}
 
}  // namespace
 
// Parse "<category>,<subject>,<date>" and push it. O(log n).
bool CeoInbox::addEmail(const std::string& args) {
    std::size_t c1 = args.find(',');                        // end of category
    std::size_t c2 = args.rfind(',');                       // start of date
    if (c1 == std::string::npos || c2 == c1) return false;  // need two commas
    std::string cat  = trim(args.substr(0, c1));            // trimmed category
    std::string subj = args.substr(c1 + 1, c2 - c1 - 1);    // subject kept as given
    std::string date = trim(args.substr(c2 + 1));           // trimmed date
 
    int rank = rankOf(cat);
    int key = 0;
    if (rank < 0 || !parseDate(date, key)) return false;    // bad category or date
 
    heap_.push(Email(cat, subj, date, rank, key, nextSeq_++));
    return true;
}
 
// Show the highest-priority email. O(1).
void CeoInbox::next() const {
    if (heap_.empty()) { std::cout << "No emails to read.\n"; return; }
    const Email& e = heap_.top();
    std::cout << "Next email:\n"
              << "Sender: "  << e.category() << '\n'
              << "Subject: " << e.subject()  << '\n'
              << "Date: "    << e.date()     << '\n';
}
 
// Discard the highest-priority email. O(log n).
void CeoInbox::read() { if (!heap_.empty()) heap_.pop(); }
 
// Print the unread count. O(1).
void CeoInbox::count() const {
    std::cout << "There are " << heap_.size() << " emails to read.\n";
}
 
// Category name -> rank (higher is read sooner).
int CeoInbox::rankOf(const std::string& c) {
    if (c == "Boss")            return 4;
    if (c == "Subordinate")     return 3;
    if (c == "Peer")            return 2;
    if (c == "ImportantPerson") return 1;
    if (c == "OtherPerson")     return 0;
    return -1;
}
 
// Strict MM-DD-YYYY: exactly 10 chars, digits and two dashes, month 1-12,
// day 1-31, 4-digit year. Writes YYYYMMDD to key. O(1).
bool CeoInbox::parseDate(const std::string& s, int& key) {
    if (s.size() != 10 || s[2] != '-' || s[5] != '-') return false;  // shape check
    for (std::size_t i = 0; i < s.size(); ++i) {
        if (i == 2 || i == 5) continue;                              // skip dashes
        if (s[i] < '0' || s[i] > '9') return false;                  // digits only
    }
    int m = (s[0] - '0') * 10 + (s[1] - '0');                        // month
    int d = (s[3] - '0') * 10 + (s[4] - '0');                        // day
    int y = (s[6] - '0') * 1000 + (s[7] - '0') * 100
          + (s[8] - '0') * 10 + (s[9] - '0');                        // year
    if (m < 1 || m > 12 || d < 1 || d > 31 || y < 1000) return false;
    key = y * 10000 + m * 100 + d;                                   // sortable key
    return true;
}