/*
 * File:           CeoInbox.h
 * Program:        EECS 348 Assignment 3 - CEO Email Prioritizer
 * Description:    Declares CeoInbox, which owns the heap and implements EMAIL/NEXT/READ/COUNT.
 * Inputs/Output:  None (declarations)
 * Collaborators:  None
 * Other sources:  Code generated by Claude (Anthropic LLM), then reviewed by me.
 * Author:         Jacob Fox
 * Creation date:  09-30-2026
 * Revision date:  09-30-2026
 * Revisions:      Split single-file version into modules.
 */


#ifndef CEOINBOX_H
#define CEOINBOX_H
 
#include <cstdint>
#include <string>
 
#include "Email.h"
#include "MaxHeap.h"
 
class CeoInbox {
public:
    // EMAIL: args is the text after "EMAIL ". Returns false if malformed.
    bool addEmail(const std::string& args);
    void next() const;   // NEXT: show the top email without removing it
    void read();         // READ: discard the top email (no-op if empty)
    void count() const;  // COUNT: print the number of unread emails
 
private:
    MaxHeap<Email> heap_;        // the priority queue
    std::uint64_t nextSeq_ = 0;  // arrival counter for tie-breaking
 
    static int rankOf(const std::string& category);  // -1 if unknown
    // Strictly parse MM-DD-YYYY into a YYYYMMDD sort key; false if invalid.
    static bool parseDate(const std::string& s, int& key);
};
 
#endif  // CEOINBOX_H