/*
 * File:           Email.cpp
 * Program:        EECS 348 Assignment 3 - CEO Email Prioritizer
 * Description:    Implements Email construction and priority comparison.
 * Inputs/Output:  None
 * Collaborators:  None
 * Other sources:  Code generated by Claude (Anthropic LLM), then reviewed by me.
 * Author:         Jacob Fox
 * Creation date:  09-30-2026
 * Revision date:  09-30-2026
 * Revisions:      Split single-file version into modules.
 */

#include "Email.h"

#include <utility>  // std::move

// Pack rank and date into one key; strings are moved, not copied.
Email::Email(std::string category, std::string subject, std::string date,
             int rank, int dateKey, std::uint64_t seq)
    : category_(std::move(category)), subject_(std::move(subject)),
      date_(std::move(date)),
      key_(static_cast<std::int64_t>(rank) * kRankScale + dateKey),
      seq_(seq) {}

// Larger key wins; on equal keys the smaller (earlier) seq wins.
bool Email::higherPriorityThan(const Email& o) const {
    return key_ != o.key_ ? key_ > o.key_ : seq_ < o.seq_;
}
