/*
 * File:           Email.h
 * Program:        EECS 348 Assignment 3 - CEO Email Prioritizer
 * Description:    Declares Email: one message with its priority packed into a single integer key.
 * Inputs/Output:  None (data class)
 * Collaborators:  None
 * Other sources:  Code generated by Claude (Anthropic LLM), then reviewed by me.
 * Author:         Jacob Fox
 * Creation date:  09-30-2026
 * Revision date:  09-30-2026
 * Revisions:      Split single-file version into modules.
 */

#ifndef EMAIL_H
#define EMAIL_H

#include <cstdint>
#include <string>

// Priority = rank * 1e8 + YYYYMMDD, so comparisons are O(1) integer math.
class Email {
public:
    Email(std::string category, std::string subject, std::string date,
          int rank, int dateKey, std::uint64_t seq);

    // True if this email should be read before o (better rank, then newer date,
    // then earlier arrival to break exact ties).
    bool higherPriorityThan(const Email& o) const;

    // Read-only accessors used for display.
    const std::string& category() const { return category_; }
    const std::string& subject()  const { return subject_; }
    const std::string& date()     const { return date_; }

private:
    static constexpr std::int64_t kRankScale = 100000000LL;  // > any YYYYMMDD value
    std::string category_;  // sender category as given in the file
    std::string subject_;   // subject line (may contain spaces)
    std::string date_;      // original MM-DD-YYYY text, echoed on output
    std::int64_t key_;      // rank * 1e8 + YYYYMMDD
    std::uint64_t seq_;     // arrival order, used only to break exact ties
};

#endif  // EMAIL_H
