/*
 * File:           main.cpp
 * Program:        EECS 348 Assignment 3 - CEO Email Prioritizer
 * Description:    Entry point: reads commands line by line and dispatches them to CeoInbox.
 * Inputs/Output:  Test file path (argv[1]) or stdin; output comes from CeoInbox
 * Collaborators:  None
 * Other sources:  Code generated by Claude (Anthropic LLM), then reviewed by me.
 * Author:         Jacob Fox
 * Creation date:  09-30-2026
 * Revision date:  09-30-2026
 * Revisions:      Split single-file version into modules. Added a Makefile just in case. 
 */

#include <fstream>
#include <iostream>
#include <string>

#include "CeoInbox.h"

int main(int argc, char* argv[]) {
    std::ifstream file;  // used only if a path is given
    if (argc > 1) {
        file.open(argv[1]);
        if (!file) { std::cerr << "Cannot open " << argv[1] << '\n'; return 1; }
    }
    std::istream& in = (argc > 1) ? static_cast<std::istream&>(file) : std::cin;

    CeoInbox inbox;
    std::string line;
    bool first = true; //added
    const std::string kEmail = "EMAIL ";  // command prefix (note trailing space)

    while (std::getline(in, line)) {
        if (first) { first = false; if (line.compare(0, 3, "\xEF\xBB\xBF") == 0) line.erase(0, 3); }
        while (!line.empty() && (line.back() == '\r' || line.back() == ' ' || line.back() == '\t'))
            line.pop_back();  // tolerate CRLF and trailing whitespace  // tolerate CRLF

        if (line.compare(0, kEmail.size(), kEmail) == 0) {
            if (!inbox.addEmail(line.substr(kEmail.size())))
                std::cerr << "Skipping malformed line: " << line << '\n';
        } else if (line == "NEXT")  inbox.next();
        else if (line == "READ")    inbox.read();
        else if (line == "COUNT")   inbox.count();
        // Blank/unrecognized lines are ignored.
    }
    return 0;
}
