/*
 * File:           MaxHeap.h
 * Program:        EECS 348 Assignment 3 - CEO Email Prioritizer
 * Description:    Generic array-based MaxHeap (header-only because it is a template). T must provide higherPriorityThan(const T&).
 * Inputs/Output:  None (library class)
 * Collaborators:  None
 * Other sources:  Code generated by Claude (Anthropic LLM), then reviewed by me.
 * Author:         Jacob Fox
 * Creation date:  09-30-2026
 * Revision date:  09-30-2026
 * Revisions:      Split single-file version into modules.
 */

#ifndef MAXHEAP_H
#define MAXHEAP_H

#include <cstddef>  // std::size_t
#include <utility>  // std::move, std::swap
#include <vector>   // contiguous storage for the heap array

// Binary heap on an array: children of i are 2i+1 and 2i+2, parent is (i-1)/2.
template <typename T>
class MaxHeap {
public:
    bool empty() const { return data_.empty(); }       // O(1)
    std::size_t size() const { return data_.size(); }  // O(1)

    // O(log n): append at the end, then bubble up.
    void push(T item) {
        data_.push_back(std::move(item));
        siftUp(data_.size() - 1);
    }

    // O(1): highest-priority element. Caller must ensure !empty().
    const T& top() const { return data_.front(); }

    // O(log n): last element replaces the root, then sinks. Caller must ensure !empty().
    void pop() {
        data_.front() = std::move(data_.back());  // last element replaces root
        data_.pop_back();                         // shrink the array
        if (!data_.empty()) siftDown(0);          // restore heap order
    }

private:
    std::vector<T> data_;  // the heap array

    // Move element at i up while it outranks its parent.
    void siftUp(std::size_t i) {
        while (i > 0) {
            std::size_t parent = (i - 1) / 2;
            if (!data_[i].higherPriorityThan(data_[parent])) break;
            std::swap(data_[i], data_[parent]);
            i = parent;
        }
    }

    // Move element at i down while a child outranks it.
    void siftDown(std::size_t i) {
        const std::size_t n = data_.size();
        for (;;) {
            std::size_t best = i, l = 2 * i + 1, r = l + 1;
            if (l < n && data_[l].higherPriorityThan(data_[best])) best = l;
            if (r < n && data_[r].higherPriorityThan(data_[best])) best = r;
            if (best == i) break;  // heap property holds
            std::swap(data_[i], data_[best]);
            i = best;
        }
    }
};

#endif  // MAXHEAP_H
