/*
 * Program:        EECS 348 Assignment 3 - CEO Email Prioritizer
 * Description:    C++ program that prioritizes emails for a busy CEO using a
 *                 hand-written, array-based MaxHeap acting as a priority queue.
 *                 Priority: Boss > Subordinate > Peer > ImportantPerson > OtherPerson;
 *                 within the same category, the NEWEST email comes first.
 * Inputs:         Test file path (argv[1], or stdin if omitted). Commands:
 *                   EMAIL <category>,<subject>,<MM-DD-YYYY>
 *                   NEXT | READ | COUNT
 * Output:         Terminal output for NEXT and COUNT (see printEmail / main).
 * Collaborators:  None
 * Other sources:  Code generated by Claude (Anthropic LLM), then reviewed by author.
 * Author:         <YOUR NAME HERE>
 * Creation date:  <MM-DD-YYYY>
 * Revision date:  <MM-DD-YYYY>
 * Revisions:      Initial version.
 *
 * Complexity:     EMAIL O(log n), NEXT O(1), READ O(log n), COUNT O(1).
 *                 Space O(n) (one heap slot per unread email).
 *
 * Authorship key used in block comments below:
 *   [AI] = generated by Claude, [ME] = author-written/modified.
 */

#include <cstdint>   // fixed-width integer types
#include <cstdio>    // sscanf
#include <fstream>   // reading the test file
#include <iostream>  // terminal I/O
#include <string>    // std::string
#include <utility>   // std::move, std::swap
#include <vector>    // contiguous storage for the heap array

// ---------------------------------------------------------------------------
// [AI] Email: one message. Priority is packed into a single integer so every
// heap comparison is O(1) integer math instead of string/date comparison.
// ---------------------------------------------------------------------------
class Email {
public:
    Email(std::string category, std::string subject, std::string date,
          int rank, int dateKey, std::uint64_t seq)
        : category_(std::move(category)), subject_(std::move(subject)),
          date_(std::move(date)),
          key_(static_cast<std::int64_t>(rank) * kRankScale + dateKey),
          seq_(seq) {}

    // Strict "higher priority than" test used by the heap.
    // Larger key wins (better category, then newer date); ties go to the
    // email that arrived first (smaller seq_) so behavior is deterministic.
    bool higherPriorityThan(const Email& o) const {
        return key_ != o.key_ ? key_ > o.key_ : seq_ < o.seq_;
    }

    // Read-only accessors for display.
    const std::string& category() const { return category_; }
    const std::string& subject()  const { return subject_; }
    const std::string& date()     const { return date_; }

private:
    static constexpr std::int64_t kRankScale = 100000000LL; // > any YYYYMMDD value
    std::string category_;  // sender category as given in the file
    std::string subject_;   // subject line (may contain spaces)
    std::string date_;      // original MM-DD-YYYY text, echoed on output
    std::int64_t key_;      // rank * 1e8 + YYYYMMDD
    std::uint64_t seq_;     // arrival order, used only to break exact ties
};

// ---------------------------------------------------------------------------
// [AI] MaxHeap: array-based binary heap, built from scratch (no std::*heap).
// Element at index i has children 2i+1 and 2i+2 and parent (i-1)/2.
// T must provide higherPriorityThan(const T&).
// ---------------------------------------------------------------------------
template <typename T>
class MaxHeap {
public:
    bool empty() const { return data_.empty(); }
    std::size_t size() const { return data_.size(); }

    // O(log n): append at the end, then bubble up.
    void push(T item) {
        data_.push_back(std::move(item));
        siftUp(data_.size() - 1);
    }

    // O(1): highest-priority element. Caller must ensure !empty().
    const T& top() const { return data_.front(); }

    // O(log n): remove root by moving the last element there, then sift down.
    // Caller must ensure !empty().
    void pop() {
        data_.front() = std::move(data_.back()); // last element replaces root
        data_.pop_back();                        // shrink the array
        if (!data_.empty()) siftDown(0);         // restore heap order
    }

private:
    std::vector<T> data_;  // the heap array

    // Move element at i up while it outranks its parent.
    void siftUp(std::size_t i) {
        while (i > 0) {
            std::size_t parent = (i - 1) / 2;
            if (!data_[i].higherPriorityThan(data_[parent])) break;
            std::swap(data_[i], data_[parent]);
            i = parent;
        }
    }

    // Move element at i down while a child outranks it.
    void siftDown(std::size_t i) {
        const std::size_t n = data_.size();
        for (;;) {
            std::size_t best = i, l = 2 * i + 1, r = l + 1;
            if (l < n && data_[l].higherPriorityThan(data_[best])) best = l;
            if (r < n && data_[r].higherPriorityThan(data_[best])) best = r;
            if (best == i) break;               // heap property holds
            std::swap(data_[i], data_[best]);
            i = best;
        }
    }
};

// ---------------------------------------------------------------------------
// [AI] CeoInbox: owns the heap and implements the four commands.
// ---------------------------------------------------------------------------
class CeoInbox {
public:
    // Handle "EMAIL <category>,<subject>,<date>"; args is everything after "EMAIL ".
    // Returns false (and stores nothing) if the line is malformed.
    bool addEmail(const std::string& args) {
        std::size_t c1 = args.find(',');                         // end of category
        std::size_t c2 = args.rfind(',');                        // start of date
        if (c1 == std::string::npos || c2 == c1) return false;   // need two commas
        std::string cat  = args.substr(0, c1);
        std::string subj = args.substr(c1 + 1, c2 - c1 - 1);
        std::string date = args.substr(c2 + 1);

        int rank = rankOf(cat);
        int m, d, y;
        if (rank < 0 || std::sscanf(date.c_str(), "%d-%d-%d", &m, &d, &y) != 3)
            return false;                                        // bad category/date

        heap_.push(Email(cat, subj, date, rank, y * 10000 + m * 100 + d, nextSeq_++));
        return true;
    }

    // NEXT: show (but keep) the highest-priority email.
    void next() const {
        if (heap_.empty()) { std::cout << "No emails to read.\n"; return; }
        const Email& e = heap_.top();
        std::cout << "Next email:\n"
                  << "Sender: "  << e.category() << '\n'
                  << "Subject: " << e.subject()  << '\n'
                  << "Date: "    << e.date()     << '\n';
    }

    // READ: discard the highest-priority email; silently ignored if empty.
    void read() { if (!heap_.empty()) heap_.pop(); }

    // COUNT: number of unread emails.
    void count() const {
        std::cout << "There are " << heap_.size() << " emails to read.\n";
    }

private:
    MaxHeap<Email> heap_;        // the priority queue
    std::uint64_t nextSeq_ = 0;  // arrival counter for tie-breaking

    // Map category name to rank (higher = read sooner); -1 if unknown.
    static int rankOf(const std::string& c) {
        if (c == "Boss")            return 4;
        if (c == "Subordinate")     return 3;
        if (c == "Peer")            return 2;
        if (c == "ImportantPerson") return 1;
        if (c == "OtherPerson")     return 0;
        return -1;
    }
};

// ---------------------------------------------------------------------------
// [AI] main: stream the input line by line and dispatch commands.
// ---------------------------------------------------------------------------
int main(int argc, char* argv[]) {
    std::ifstream file;                       // used only if a path is given
    if (argc > 1) {
        file.open(argv[1]);
        if (!file) { std::cerr << "Cannot open " << argv[1] << '\n'; return 1; }
    }
    std::istream& in = (argc > 1) ? static_cast<std::istream&>(file) : std::cin;

    CeoInbox inbox;
    std::string line;
    const std::string kEmail = "EMAIL ";      // command prefix (note trailing space)

    while (std::getline(in, line)) {
        if (!line.empty() && line.back() == '\r') line.pop_back();  // tolerate CRLF files

        if (line.compare(0, kEmail.size(), kEmail) == 0) {
            if (!inbox.addEmail(line.substr(kEmail.size())))
                std::cerr << "Skipping malformed line: " << line << '\n';
        } else if (line == "NEXT")  inbox.next();
        else if (line == "READ")    inbox.read();
        else if (line == "COUNT")   inbox.count();
        // Blank/unrecognized lines are ignored.
    }
    return 0;
}